import type { Metadata } from 'next';
import { Fira_Code } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import { Provider } from './utils/Provider';

const firaCode = Fira_Code({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${firaCode.className} h-full bg-amber-50 text-indigo-950 dark:bg-slate-950 dark:text-slate-50 dark:selection:bg-purple-500 transition-colors`}
			>
				{/* <Provider attribute='class'> */}
				<Provider>
					<main className='mx-auto max-w-5xl px-6'>
						<Navbar />
						{children}
					</main>
				</Provider>
			</body>
		</html>
	);
}
